{% set name = "polyfactory" %}
{% set version = "2.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polyfactory-{{ version }}.tar.gz
  sha256: a3ff5263756ad74acf4001f04c1b6aab7d1197cbaa070352df79573a8dcd85ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - hatchling
    - pip
  run:
    - python >=3.8,<4.0
    - faker
    - typing-extensions

test:
  imports:
    - polyfactory
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/litestar-org/polyfactory
  summary: Mock data generation factories
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivergara
