{% set name = "polyfactory" %}
{% set version = "2.22.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/polyfactory-{{ version }}.tar.gz
  sha256: ae57d07408d1f7609031a83827c7980ce32104535e146cac2253988d0a7665e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - faker
    - typing-extensions

test:
  imports:
    - polyfactory
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/litestar-org/polyfactory
  summary: Mock data generation factories
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ivergara
